server.port=8088
spring.application.name=Customer
server.servlet.context-path=/customer

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/customer
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.liquibase.enabled=true

# adc-service.location=http://localhost:8081/location
adc-service.location=http://location/location
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://identity.local/realms/Identity

#Keycloak
keycloak.auth-server-url=http://identity.local
keycloak.realm=Identity
keycloak.resource=customer-management
keycloak.credentials.secret=VMG9bsXmILYGGreSMO51AVoXTlE14rvb

#Swagger
springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true
springdoc.swagger-ui.oauth.client-id=swagger-ui
springdoc.oauthflow.authorization-url=http://identity.local/realms/Identity/protocol/openid-connect/auth
springdoc.oauthflow.token-url=http://identity.local/realms/Identity/protocol/openid-connect/token

spring.graphql.cors.allowed-origins=*

logging.level.org.springframework.security=DEBUG




