spring:
  application:
    name: backoffice-bff
  threads:
    virtual:
      enabled: on
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: backoffice-bff
            client-secret: snrHtzEP06UEcgntFihYwt2Ro9eCJnU9
            provider: keycloak
            redirect-uri: "http://backoffice.local/login/oauth2/code/keycloak"
        provider:
          keycloak:
            issuer-uri: http://identity/realms/Identity
            token-uri: http://identity/realms/Identity/protocol/openid-connect/token

server:
  port: 8089
  servlet:
    context-path: /backoffice-bff

---
# ── PROD profile ─────────────────────────────────────────────────────────────
spring:
  config:
    activate:
      on-profile: prod
  cloud:
    gateway:
      routes:
        - id: backoffice-api
          uri: http://api.local
          predicates:
            - Path=/api/**
          filters:
            - TokenRelay=
            - StripPrefix=1

        - id: backoffice-nextjs
          uri: http://backoffice-nextjs:3001
          predicates:
            - Path=/**
          filters:
            - TokenRelay=

---
# ── DEV profile ──────────────────────────────────────────────────────────────
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    gateway:
      routes:
        - id: backoffice-api-dev
          uri: http://host.docker.internal:8080
          predicates:
            - Path=/api/product/**
          filters:
            - TokenRelay=
            - StripPrefix=1

        - id: backoffice-cart-dev
          uri: http://host.docker.internal:8084
          predicates:
            - Path=/api/cart/**
          filters:
            - TokenRelay=
            - StripPrefix=1

        - id: backoffice-customer-dev
          uri: http://host.docker.internal:8088
          predicates:
            - Path=/api/customer/**
          filters:
            - TokenRelay=
            - StripPrefix=1

        - id: backoffice-order-dev
          uri: http://host.docker.internal:8085
          predicates:
            - Path=/api/order/**
          filters:
            - TokenRelay=
            - StripPrefix=1

        - id: backoffice-nextjs-dev
          uri: http://host.docker.internal:3001
          predicates:
            - Path=/**
          filters:
            - TokenRelay=
