spring.application.name=inventory

server.port=8086
server.servlet.context-path=/inventory

spring.threads.virtual.enabled=true

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/inventory
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto= none

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://identity.local/realms/Identity

springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.path=/v3/api-docs
springdoc.packages-to-scan=com.adc.inventory
springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true
springdoc.swagger-ui.oauth.client-id=swagger-ui
springdoc.oauthflow.authorization-url=http://identity.local/realms/Identity/protocol/openid-connect/auth
springdoc.oauthflow.token-url=http://identity.local/realms/Identity/protocol/openid-connect/token

spring.graphql.cors.allowed-origins=*

# service.product=http://localhost:8080/product
# service.location=http://localhost:8081/location
service.product=http://api.local/product
service.location=http://api.local/location