spring.application.name=cart
spring.threads.virtual.enabled=true
server.port=8084
server.servlet.context-path=/cart

#Prod
adc.services.service-url=http://media/media
adc.services.product=http://product/product

# adc.services.media=http://localhost:8083/media
# adc.services.product=http://localhost:8080/product

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/cart
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.liquibase.enabled=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://identity.local/realms/Identity

springdoc.swagger-ui.path=/swagger-ui
springdoc.packagesToScan=com.adc.cart
springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true
springdoc.swagger-ui.oauth.client-id=swagger-ui
springdoc.oauthflow.authorization-url=http://identity.local/realms/Identity/protocol/openid-connect/auth
springdoc.oauthflow.token-url=http://identity.local/realms/Identity/protocol/openid-connect/token

spring.graphql.cors.allowed-origins=*